### ISSUE TITLE
初回レンダリング時に重複したリクエストが発生する

### ISSUE THREAD

**Issue by aijkl** [yoshi-non/github-contribution-graph#97]
表題の通りでリクエストとレスポンスともに同一の重複した通信があります。
useEfect周りで何かありそう、何もコードを読んでないので意図したものであれば申し訳ない
<img width="1053" alt="image" src="https://github.com/yoshi-non/github-contribution-graph/assets/51302983/a84b958f-a646-4ef7-b74d-4c8477b44bbf">

**Comment by yoshi-non** [comment]
バグですね
対応します。

**Comment by yoshi-non** [comment]
<img width="483" alt="image" src="https://github.com/yoshi-non/github-contribution-graph/assets/83369665/63e66c43-a87d-4a42-acc4-4f3723f660e0">

### 発生する原因
グラフに描画する日付だけ別でデータを取得しているためそれが重複しているように見える

### 解決方法
contributionデータを取得する際に一緒に日付データも入れてしまう。
